### ISSUE TITLE
Support for linked object fields

### ISSUE THREAD

**Issue by glotchimo** [tzmfreedom/go-soql-driver#1]
SOQL query `q` is as follows:
```sql
SELECT
  OpportunityId,
  Opportunity.Name
FROM
  OpportunitySplit
WHERE
  SplitTypeId = '149d0000000TN1y'
  AND SplitAmount >= 1.00
  AND Opportunity.Type IN ('New Business', 'Add On')
  AND Opportunity.Stage_Number__c IN ('0', '1', '2', '3', '4', '5', '6')
  AND Opportunity.CloseDate IN (THIS_FISCAL_YEAR, NEXT_FISCAL_YEAR)
```
The `OpportunitySplit` object has a linked `OpportunityObject`. In SOQL, you can reference the field of a linked object via dot notation, as written in the selection clause above.

I am processing `q` via `sqlx` as such:
```go
rows, err := db.Queryx(q)
if err != nil {
	return nil, err
}

var records [][]interface{}
for rows.Next() {
	record, err := rows.SliceScan()
	if err != nil {
		return nil, err
	}

	records = append(records, record)
}
```

It appears as if the `Opportunity` is being parsed into a `soapforce.SObject`, but that instance appears to be empty in the results of the above process.

Is there a simple way/would it be a simple implementation to, rather than deserialize nested values to fields within a `soapforce.SObject`, deserialize nested values directly to a type, in this case a `string`?

**Comment by tzmfreedom** [comment]
@elliott-maguire Thank you for letting me know!!
It's bug for relation query and I'll fix it.

**Comment by tzmfreedom** [comment]
@elliott-maguire I've fixed it https://github.com/tzmfreedom/go-soql-driver/commit/bfb422e69ff9e9f9f0e03e5763b7dfa04c099dcb

**Comment by glotchimo** [comment]
Indeed you have, thank you!
